# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\"U\n\x08\x44iscover\x12\x13\n\x0b\x64\x65vice_type\x18\x01 \x01(\t\x12\x1a\n\x12\x63ommunication_type\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\x05\"\x14\n\x04\x44\x61ta\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"-\n\x07\x43ommand\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x11\n\targuments\x18\x02 \x03(\t\"2\n\x0f\x43ommandResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"E\n\x06\x44\x65vice\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x65vice_type\x18\x02 \x01(\t\x12\x1a\n\x12\x63ommunication_type\x18\x03 \x01(\t\"&\n\nDeviceList\x12\x18\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x07.Device\"\xe2\x01\n\x07Message\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x1d\n\x08\x64iscover\x18\x02 \x01(\x0b\x32\t.DiscoverH\x00\x12\x15\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x05.DataH\x00\x12\x1b\n\x07\x63ommand\x18\x04 \x01(\x0b\x32\x08.CommandH\x00\x12,\n\x10\x63ommand_response\x18\x05 \x01(\x0b\x32\x10.CommandResponseH\x00\x12\x19\n\x06\x64\x65vice\x18\x06 \x01(\x0b\x32\x07.DeviceH\x00\x12\"\n\x0b\x64\x65vice_list\x18\x07 \x01(\x0b\x32\x0b.DeviceListH\x00\x42\t\n\x07\x63ontent')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DISCOVER._serialized_start=17
  _DISCOVER._serialized_end=102
  _DATA._serialized_start=104
  _DATA._serialized_end=124
  _COMMAND._serialized_start=126
  _COMMAND._serialized_end=171
  _COMMANDRESPONSE._serialized_start=173
  _COMMANDRESPONSE._serialized_end=223
  _DEVICE._serialized_start=225
  _DEVICE._serialized_end=294
  _DEVICELIST._serialized_start=296
  _DEVICELIST._serialized_end=334
  _MESSAGE._serialized_start=337
  _MESSAGE._serialized_end=563
# @@protoc_insertion_point(module_scope)
