# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/air_conditioner.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bproto/air_conditioner.proto\"D\n\x18\x43hangeTemperatureRequest\x12\x18\n\x0btemperature\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x0e\n\x0c_temperature\"\x17\n\x15GetTemperatureRequest\"Z\n\x16\x41irConditionerResponse\x12\x13\n\x06status\x18\x01 \x01(\x08H\x00\x88\x01\x01\x12\x14\n\x07message\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\t\n\x07_statusB\n\n\x08_message2\xa2\x01\n\x0e\x41irConditioner\x12J\n\x12\x63hange_temperature\x12\x19.ChangeTemperatureRequest\x1a\x17.AirConditionerResponse\"\x00\x12\x44\n\x0fget_temperature\x12\x16.GetTemperatureRequest\x1a\x17.AirConditionerResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.air_conditioner_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHANGETEMPERATUREREQUEST._serialized_start=31
  _CHANGETEMPERATUREREQUEST._serialized_end=99
  _GETTEMPERATUREREQUEST._serialized_start=101
  _GETTEMPERATUREREQUEST._serialized_end=124
  _AIRCONDITIONERRESPONSE._serialized_start=126
  _AIRCONDITIONERRESPONSE._serialized_end=216
  _AIRCONDITIONER._serialized_start=219
  _AIRCONDITIONER._serialized_end=381
# @@protoc_insertion_point(module_scope)
