# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import blind_curtain_pb2 as proto_dot_blind__curtain__pb2


class BlindCurtainStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.change_state = channel.unary_unary(
                '/BlindCurtain/change_state',
                request_serializer=proto_dot_blind__curtain__pb2.ChangeBlindCurtainStateRequest.SerializeToString,
                response_deserializer=proto_dot_blind__curtain__pb2.BlindCurtainResponse.FromString,
                )
        self.get_state = channel.unary_unary(
                '/BlindCurtain/get_state',
                request_serializer=proto_dot_blind__curtain__pb2.GetBlindCurtainStateRequest.SerializeToString,
                response_deserializer=proto_dot_blind__curtain__pb2.BlindCurtainResponse.FromString,
                )


class BlindCurtainServicer(object):
    """Missing associated documentation comment in .proto file."""

    def change_state(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_state(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BlindCurtainServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'change_state': grpc.unary_unary_rpc_method_handler(
                    servicer.change_state,
                    request_deserializer=proto_dot_blind__curtain__pb2.ChangeBlindCurtainStateRequest.FromString,
                    response_serializer=proto_dot_blind__curtain__pb2.BlindCurtainResponse.SerializeToString,
            ),
            'get_state': grpc.unary_unary_rpc_method_handler(
                    servicer.get_state,
                    request_deserializer=proto_dot_blind__curtain__pb2.GetBlindCurtainStateRequest.FromString,
                    response_serializer=proto_dot_blind__curtain__pb2.BlindCurtainResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BlindCurtain', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BlindCurtain(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def change_state(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BlindCurtain/change_state',
            proto_dot_blind__curtain__pb2.ChangeBlindCurtainStateRequest.SerializeToString,
            proto_dot_blind__curtain__pb2.BlindCurtainResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_state(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BlindCurtain/get_state',
            proto_dot_blind__curtain__pb2.GetBlindCurtainStateRequest.SerializeToString,
            proto_dot_blind__curtain__pb2.BlindCurtainResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
