# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/blind_curtain.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/blind_curtain.proto\">\n\x1e\x43hangeBlindCurtainStateRequest\x12\x12\n\x05state\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_state\"\x1d\n\x1bGetBlindCurtainStateRequest\"X\n\x14\x42lindCurtainResponse\x12\x13\n\x06status\x18\x01 \x01(\x08H\x00\x88\x01\x01\x12\x14\n\x07message\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\t\n\x07_statusB\n\n\x08_message2\x9c\x01\n\x0c\x42lindCurtain\x12H\n\x0c\x63hange_state\x12\x1f.ChangeBlindCurtainStateRequest\x1a\x15.BlindCurtainResponse\"\x00\x12\x42\n\tget_state\x12\x1c.GetBlindCurtainStateRequest\x1a\x15.BlindCurtainResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.blind_curtain_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHANGEBLINDCURTAINSTATEREQUEST._serialized_start=29
  _CHANGEBLINDCURTAINSTATEREQUEST._serialized_end=91
  _GETBLINDCURTAINSTATEREQUEST._serialized_start=93
  _GETBLINDCURTAINSTATEREQUEST._serialized_end=122
  _BLINDCURTAINRESPONSE._serialized_start=124
  _BLINDCURTAINRESPONSE._serialized_end=212
  _BLINDCURTAIN._serialized_start=215
  _BLINDCURTAIN._serialized_end=371
# @@protoc_insertion_point(module_scope)
