# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/humidifier.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/humidifier.proto\"\x18\n\x16HumidifierEmptyRequest\"@\n ChangeHumiditySensorStateRequest\x12\x12\n\x05state\x18\x01 \x01(\x08H\x00\x88\x01\x01\x42\x08\n\x06_state\"s\n\x1d\x43hangeBoundsHumidifierRequest\x12\x18\n\x0bupper_bound\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x18\n\x0blower_bound\x18\x02 \x01(\x05H\x01\x88\x01\x01\x42\x0e\n\x0c_upper_boundB\x0e\n\x0c_lower_bound\"<\n\x1c\x43hangeSmartHumidifierRequest\x12\x12\n\x05state\x18\x01 \x01(\x08H\x00\x88\x01\x01\x42\x08\n\x06_state\"<\n\x1c\x43hangeHumidifierStateRequest\x12\x12\n\x05state\x18\x01 \x01(\x08H\x00\x88\x01\x01\x42\x08\n\x06_state\"V\n\x12HumidifierResponse\x12\x13\n\x06status\x18\x01 \x01(\x08H\x00\x88\x01\x01\x12\x14\n\x07message\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\t\n\x07_statusB\n\n\x08_message2\xcd\x03\n\nHumidifier\x12U\n\x1d\x63hange_smart_humidifier_state\x12\x1d.ChangeSmartHumidifierRequest\x1a\x13.HumidifierResponse\"\x00\x12\x44\n\x0c\x63hange_state\x12\x1d.ChangeHumidifierStateRequest\x1a\x13.HumidifierResponse\"\x00\x12L\n\x1aget_smart_humidifier_state\x12\x17.HumidifierEmptyRequest\x1a\x13.HumidifierResponse\"\x00\x12;\n\tget_state\x12\x17.HumidifierEmptyRequest\x1a\x13.HumidifierResponse\"\x00\x12\x46\n\rchange_bounds\x12\x1e.ChangeBoundsHumidifierRequest\x1a\x13.HumidifierResponse\"\x00\x12O\n\x13\x63hange_sensor_state\x12!.ChangeHumiditySensorStateRequest\x1a\x13.HumidifierResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.humidifier_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HUMIDIFIEREMPTYREQUEST._serialized_start=26
  _HUMIDIFIEREMPTYREQUEST._serialized_end=50
  _CHANGEHUMIDITYSENSORSTATEREQUEST._serialized_start=52
  _CHANGEHUMIDITYSENSORSTATEREQUEST._serialized_end=116
  _CHANGEBOUNDSHUMIDIFIERREQUEST._serialized_start=118
  _CHANGEBOUNDSHUMIDIFIERREQUEST._serialized_end=233
  _CHANGESMARTHUMIDIFIERREQUEST._serialized_start=235
  _CHANGESMARTHUMIDIFIERREQUEST._serialized_end=295
  _CHANGEHUMIDIFIERSTATEREQUEST._serialized_start=297
  _CHANGEHUMIDIFIERSTATEREQUEST._serialized_end=357
  _HUMIDIFIERRESPONSE._serialized_start=359
  _HUMIDIFIERRESPONSE._serialized_end=445
  _HUMIDIFIER._serialized_start=448
  _HUMIDIFIER._serialized_end=909
# @@protoc_insertion_point(module_scope)
