# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/lamp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/lamp.proto\"\x15\n\x13GetLampStateRequest\"\x15\n\x13GetLampColorRequest\"6\n\x16\x43hangeLampColorRequest\x12\x12\n\x05\x63olor\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_color\"6\n\x16\x43hangeLampStateRequest\x12\x12\n\x05state\x18\x01 \x01(\x08H\x00\x88\x01\x01\x42\x08\n\x06_state\";\n\x1b\x43hangeSmartLampStateRequest\x12\x12\n\x05state\x18\x01 \x01(\x08H\x00\x88\x01\x01\x42\x08\n\x06_state\"P\n\x0cLampResponse\x12\x13\n\x06status\x18\x01 \x01(\x08H\x00\x88\x01\x01\x12\x14\n\x07message\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\t\n\x07_statusB\n\n\x08_message2\xac\x02\n\x04Lamp\x12\x32\n\tget_state\x12\x14.GetLampStateRequest\x1a\r.LampResponse\"\x00\x12\x32\n\tget_color\x12\x14.GetLampColorRequest\x1a\r.LampResponse\"\x00\x12\x38\n\x0c\x63hange_state\x12\x17.ChangeLampStateRequest\x1a\r.LampResponse\"\x00\x12\x38\n\x0c\x63hange_color\x12\x17.ChangeLampColorRequest\x1a\r.LampResponse\"\x00\x12H\n\x17\x63hange_smart_lamp_state\x12\x1c.ChangeSmartLampStateRequest\x1a\r.LampResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.lamp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETLAMPSTATEREQUEST._serialized_start=20
  _GETLAMPSTATEREQUEST._serialized_end=41
  _GETLAMPCOLORREQUEST._serialized_start=43
  _GETLAMPCOLORREQUEST._serialized_end=64
  _CHANGELAMPCOLORREQUEST._serialized_start=66
  _CHANGELAMPCOLORREQUEST._serialized_end=120
  _CHANGELAMPSTATEREQUEST._serialized_start=122
  _CHANGELAMPSTATEREQUEST._serialized_end=176
  _CHANGESMARTLAMPSTATEREQUEST._serialized_start=178
  _CHANGESMARTLAMPSTATEREQUEST._serialized_end=237
  _LAMPRESPONSE._serialized_start=239
  _LAMPRESPONSE._serialized_end=319
  _LAMP._serialized_start=322
  _LAMP._serialized_end=622
# @@protoc_insertion_point(module_scope)
